### ISSUE TITLE
Bug en inventario

### ISSUE THREAD

**Issue by pamionj** [secret-cactus/SAI-NET#8]
Las validaciones del inventario borran todo lo que uno ha escrito en las casillas del form al clickear en aceptar el alert D=
@secret-cactus 

y aprovecho de testear como es esto de los "Issue"

**Comment by secret-cactus** [comment]
Es normal: despues de agregar el registro, limpia los campos automáticamente.

**Comment by SpiritedHunter** [comment]
me refiero a que por ejemplo coloco un  codigo, nombre y cantidad pero sin detalle....le doy agregar, sale el alert diciendo que por favor ponga el detalle pero al darle aceptar a dicho alert se borra todo lo que había puesto (codigo, nombre y cantidad que habia puesto en los campos antes de darle al botón agregar)...no sé como explicarlo mejor en palabras

**Comment by secret-cactus** [comment]
Entiendo, lo corregiré ahora. Termino la galería, hago merge y el error se va a solucionar.
